# Generated by Django 5.2.5 on 2025-08-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doce_gustu_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem',
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_url',
            field=models.CharField(default='https://placehold.co/600x400/000000/FFFFFF?text=Sem+Imagem', max_length=500),
        ),
    ]
